version: "3"
services:
  terraform:
    image: hashicorp/terraform:1.3.7
    env_file:
      - ./.env
    volumes:
      -  ./terraform:/terraform
      -  ./index.html:/index.html
      # -  ./frontend/react-app/build/index.html:/index.html
    working_dir: /terraform
    entrypoint: ash
    tty: true